easy_admin:
    site_name: 'MovieDB Nova'
    design:
        brand_color: '#1ABC9C'
        assets:
            css:
                - 'css/ezadmin.css' 
    entities:
        Casting:
            class: App\Entity\Casting
        Department:
            class: App\Entity\Department
        Genre:
            class: App\Entity\Genre
        Metier:
            class: App\Entity\Job
        Team:
            class: App\Entity\Team
            #form:
                #fields: #type: etant du type souhaité ici autocomplete
                    #- { property: 'movie', type: 'easyadmin_autocomplete' }
                    #- { property: 'person', type: 'easyadmin_autocomplete' }
                    #- { property: 'job', type: 'easyadmin_autocomplete' }
    